# Generated by Django 2.2.4 on 2019-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'flat', 'verbose_name_plural': 'flats'},
        ),
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(verbose_name='Новое здание'),
        ),
    ]
