# Generated by Django 2.2.4 on 2019-10-09 17:32

from django.db import migrations


def format_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        user_phone = flat.owners_phonenumber
        flat.owner_phone_pure = user_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(format_phones),
    ]
