# Generated by Django 2.2.4 on 2019-10-09 19:21

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        user = flat.owner
        phone = flat.owners_phonenumber
        formatted_phone = flat.owner_phone_pure
        Owner.objects.get_or_create(
            owner=user, owners_phonenumber=phone, owner_phone_pure=formatted_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]
